def CriarJdbcStore(name, prefixName, target, dataSource):
	print ('Criando JdbcStore: ' + name )
	cd('/')
	create(name,'JdbcStore')
	cd('JdbcStore/'+name)
	set('PrefixName',prefixName)
	set('Target',target)
	DataSource('Target',dataSource)

def CriarFila(type, moduleName, name, jndiName, subdeployment, priorityDestinationKey):
	print ('Criando Fila: ' + name )
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/'+ moduleName)
	if (type == 'QUEUE'):
		myq=create(name,'Queue')
	else:
		myq=create(name,'UniformDistributedQueue')
	myq.setJNDIName(jndiName)
	myq.setSubDeploymentName(subdeployment)
	if (priorityDestinationKey != 'null'):
		myq.setDestinationKeys(jarray.array([String(priorityDestinationKey)],String))

def CriarDeliveryfailure(moduleName, type, queueName, destinationKey, redeliveryDelay, redeliveryLimit):
	print ('Criando Deliveryfailure para a fila: ' + queueName )
	if (type == 'QUEUE'):
		cd('Queues/' + queueName)
		cmo = cd('DeliveryFailureParams/' + queueName)
		cmo.setRedeliveryLimit(redeliveryLimit)
		cmo.setExpirationPolicy('Redirect')
		
		cmo.setErrorDestination(getMBean('/JMSSystemResources/'+moduleName+'/JMSResource/'+moduleName+'/Queues/'+destinationKey))
		cd('..')
		cd('..')
		cmo = cd('DeliveryParamsOverrides/' + queueName)
		cmo.setRedeliveryDelay(redeliveryDelay)
	else:
		cd('UniformDistributedQueues/' + queueName)
		cmo = cd('DeliveryFailureParams/' + queueName)
		cmo.setRedeliveryLimit(redeliveryLimit)
		cmo.setExpirationPolicy('Redirect')
		print ('cmo.setErrorDestination(getMBean(''/JMSSystemResources/'+moduleName+'/JMSResource/'+moduleName+'/UniformDistributedQueues/'+destinationKey+'))')
		cmo.setErrorDestination(getMBean('/JMSSystemResources/'+moduleName+'/JMSResource/'+moduleName+'/UniformDistributedQueues/'+destinationKey))
		cd('..')
		cd('..')
		cmo = cd('DeliveryParamsOverrides/' + queueName)
		cmo.setRedeliveryDelay(redeliveryDelay)
	

def CriarAdminServer(name, port, sslPort):
	print ('Criando AdminServer: ' + name )
	cd('Servers/'+name)
	set('ListenPort',port)
	cd('SSL/AdminServer')
	set('Enabled','True')
	set('ListenPort',sslPort)

def CriarCluster(name, multicastAddress, port, address):
	print ('Criando Cluster: ' + name )
	cd('/')
	create(name,'Cluster')
	cd('Clusters/'+name)
	if (multicastAddress != 'null'):
		set('MulticastAddress',multicastAddress)
	if (port != 0):
		set('MulticastPort',port)
	if (address != 'null'):
		set('ClusterAddress',address)

def CriarFileStore(name, path, target, targetType):
	print ('Criando FileStore: ' + name )
	cd('/')
	create(name,'FileStore')
	cd('FileStores/'+name)
	set('Directory',path)
	set('Targets',jarray.array([ObjectName('com.bea:Name='+target+',Type='+targetType)], ObjectName))

def CriarJmsServer(name, persistentStore, target, targetType):
	print ('Criando JmsServer: ' + name )
	cd('/')
	create(name,'JMSServer')
	cd('JMSServers/'+name)
	set('PersistentStore',ObjectName('com.bea:Name='+persistentStore+',Type=FileStore'))
	set('Targets',jarray.array([ObjectName('com.bea:Name='+target+',Type='+targetType)], ObjectName))

def CriarTopic(moduleName, name, subdeployment, redeliveryDelay, redeliveryLimit):
	print ('Criando Topic: ' + name )
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/' + moduleName)
	top=create(name,'Topic')
	top.setJNDIName(name)
	top.setSubDeploymentName(subdeployment)
	cd('Topics/' + name)
	cd('DeliveryFailureParams/' + name)
	set('RedeliveryLimit',redeliveryLimit)
	cd('..')
	cd('..')
	cd('DeliveryParamsOverrides/' + name)
	set('RedeliveryDelay', redeliveryDelay)

def CriarPriorityDestinationKey(moduleName, name, sortKey, keyType, direction):
	print ('Criando Priority Destination Key: ' + name )
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/' + moduleName)
	create(name,'DestinationKey')
	cd('DestinationKeys/' + name)
	set('Property',sortKey)
	set('KeyType',keyType)
	set('SortOrder',direction)

def CriarManagedServer(name, port, address, machine, cluster):
	print ('Criando Managed Server: ' + name )
	cd('/')
	create(name,'Server')
	cd('Servers/' + name)
	set('ListenPort',port)
	if (cluster != 'null'):
		cmo.setMachine (getMBean('/Machines/' + machine))
	set('ListenAddress',address)
	if (cluster != 'null'):
		cmo.setCluster (getMBean('/Clusters/' + cluster))

def CriarDatasource(jndiName):
	print ('Criando Datasource: ' + jndiName )
	cd('/')
	varDataSource=create(jndiName,'JDBCSystemResource')
	cd('JDBCSystemResources/' + jndiName + '/JDBCResource/' + jndiName)
	set('Name',jndiName)

def CriarJmsModule(name):
	print ('Criando JmsModulo: ' + name )
	cd('/')
	create(name,'JMSSystemResource')
	cd('JMSSystemResources/' + name)

def CriarConnectionfactory(moduleName, name, jndiName, reconnectPolicy, maxMessagesPerSession, isServerAffinityEnabled, isXAConnectionFactoryEnabled, sendTimeout):
	print ('Criando Connection Factory: ' + name )
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/' + moduleName)
	create(name,'ConnectionFactory')
	cd('ConnectionFactories/' + jndiName)
	set('JNDIName',jndiName)
	set('DefaultTargetingEnabled','true')
	cd('ClientParams/' + jndiName)
	set('ReconnectPolicy',reconnectPolicy)
	set('MessagesMaximum',maxMessagesPerSession)
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/' + moduleName)
	cd('ConnectionFactories/' + jndiName)
	cd('LoadBalancingParams/' + jndiName)
	set('ServerAffinityEnabled',isServerAffinityEnabled)
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/' + moduleName)
	cd('ConnectionFactories/' + jndiName)
	cd('TransactionParams/' + jndiName)
	set('XAConnectionFactoryEnabled',isXAConnectionFactoryEnabled)
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/' + moduleName)
	cd('ConnectionFactories/' + jndiName)
	cd('DefaultDeliveryParams/' + jndiName)
	set('SendTimeout',sendTimeout)

def CriarConnectionPool(datasourceName, driverClassName, url, dbPassword, dbUsername, inCapacity, maxCapacity, incrementCapacity, isTestConnReserve, testTableName, shrinkFrequency, connCreationRetryFrequency, incativeConnectionTimeoutSeconds, connReserveTimeout, maxCapacityInit, minCapacityInit, statementCache, testFrequency, supportsGlobal):
	print ('Criando Connection Pool para datasource: ' + datasourceName )
	cd('JDBCDriverParams/' + datasourceName)
	set('DriverName',driverClassName)
	set('Url',url)
	set('PasswordEncrypted',dbPassword)
	cd('Properties/' + datasourceName)
	create('user','Property')
	cd('Properties/user')
	cmo.setValue(dbUsername)
	cd('/JDBCSystemResources/' + datasourceName + '/JDBCResource/' + datasourceName)
	cd('JDBCDataSourceParams/' + datasourceName)
	set('JNDINames',jarray.array([String(datasourceName)], String))
	if (supportsGlobal == 'true'):
		set('GlobalTransactionsProtocol', java.lang.String('None'))
	else:
		set('GlobalTransactionsProtocol', java.lang.String('LoggingLastResource'))
	cd('/JDBCSystemResources/' + datasourceName + '/JDBCResource/' + datasourceName)
	cd('JDBCConnectionPoolParams/' + datasourceName)
	set('InitialCapacity',inCapacity)
	set('MaxCapacity',maxCapacity)
	set('MinCapacity',minCapacityInit)
	set('StatementCacheSize',statementCache)
	set('TestFrequencySeconds',testFrequency)
	set('HighestNumWaiters',maxCapacity)
	set('CapacityIncrement',incrementCapacity)
	set('TestConnectionsOnReserve',isTestConnReserve)
	set('TestTableName',testTableName)
	set('ShrinkFrequencySeconds',shrinkFrequency)
	set('ConnectionCreationRetryFrequencySeconds',connCreationRetryFrequency)
	if (incativeConnectionTimeoutSeconds != 0):
		set('InactiveConnectionTimeoutSeconds',incativeConnectionTimeoutSeconds)
	set('ConnectionReserveTimeoutSeconds',connReserveTimeout)
	if(datasourceName == 'sis.TempDataSource'):
		cd('/JDBCSystemResources/'+datasourceName+'/JDBCResource/'+datasourceName+'/JDBCXAParams/'+datasourceName)
		set('XaSetTransactionTimeout', 'true')
		cmo.setXaTransactionTimeout(600)

def CriarSubDeployment(name, subName):
	print ('Criando SubDeployment: ' + name )
	cd('/')
	cd('JMSSystemResources/' + name)
	create(subName,'SubDeployment')
	cd('SubDeployments/' + subName)

def CriarTemplate(moduleName, templateName, templateDestinationKey):
	print ('Criando Template: ' + moduleName )
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/'+ moduleName)
	create(templateName,'Template')
	cd('Templates/' + templateName)
	set('DestinationKeys',jarray.array([String(templateDestinationKey)], String))

def CriarWorkManager(workManagerName, domainName):
	print ('Criando WorkManager: ' + workManagerName )
	cd('/')
	name = get('Name')
	cd('SelfTuning/' + name)
	create(workManagerName,'WorkManager')
	cd('WorkManagers/' + workManagerName)
	cmo.setMinThreadsConstraint(getMBean('/SelfTuning/' + name + '/MinThreadsConstraints/' + workManagerName + 'MinThreads'))
	cmo.setMaxThreadsConstraint(getMBean('/SelfTuning/' + name + '/MaxThreadsConstraints/' + workManagerName + 'MaxThreads'))

def CriarWorkManagerMinThread(workManagerName, domainName, minCount):
	print ('Criando WorkManager: ' + workManagerName + 'MinThreads' )
	cd('/')
	name = get('Name')
	cd('SelfTuning/' + name)
	create(workManagerName+'MinThreads','MinThreadsConstraint')
	cd('MinThreadsConstraints/' + workManagerName+'MinThreads')
	cmo.setCount(int(minCount))

def CriarWorkManagerMaxThread(workManagerName, domainName, maxCount):
	print ('Criando WorkManager: ' + workManagerName + 'MaxThreads' )
	cd('/')
	name = get('Name')
	cd('SelfTuning/' + name)
	create(workManagerName+'MaxThreads','MaxThreadsConstraint')
	cd('MaxThreadsConstraints/' + workManagerName+'MaxThreads')
	cmo.setCount(int(maxCount))

def CriarBridgeTarget(name, adapterJNDIName, connectionFactoryJNDIName, connectionURL, userName, userPassword, destinationJNDIName):
	print ('Criando CriarBridgeTarget: ' + name )
	cd('/')
	cd('JMSBridgeDestinations')
	create(name)
	cd(name)
	set('AdapterJNDIName', adapterJNDIName)
	set('ConnectionFactoryJNDIName', connectionFactoryJNDIName)
	set('ConnectionURL', connectionURL)
	set('DestinationJNDIName', destinationJNDIName)
	if (userName != 'null'):
		set('UserName', userName)
	if (userPassword != 'null'):
		set('UserPassword', userPassword)

def CriarBridge(name, qualityOfService, started, selector, targetOri, targetDest, preserveMsgProperty):
	print ('Criando CriarBridge: ' + name )
	cd('/')
	cd('MessagingBridges')
	create(name)
	cd(name)
	set('QualityOfService', qualityOfService)
	set('Started', started)
	if (selector != 'null'):
		set('Selector', selector)
	set('PreserveMsgProperty', preserveMsgProperty)
	cmo.setSourceDestination(getMBean('/JMSBridgeDestinations/' + targetOri))
	cmo.setTargetDestination(getMBean('/JMSBridgeDestinations/' + targetDest))

connect('LOGIN', 'SENHA', 'msisprd40:27001')
edit()
startEdit()
CriarJmsModule('sismodule')
cd('/')
cd('JMSSystemResources/sismodule')
set('Targets',jarray.array([ObjectName('com.bea:Name=sisconnprd39a_sup,Type=Server'),ObjectName('com.bea:Name=sisconnectorbdprd,Type=Cluster'),ObjectName('com.bea:Name=sisconnectorprd,Type=Cluster')], ObjectName))
CriarConnectionfactory('sismodule','sis.JMSConnectionFactory','sis.JMSConnectionFactory','all',1,'true','true',10000)
CriarPriorityDestinationKey('sismodule','PriorityDestinationKey','JMSPriority','Long','Descending')
CriarFileStore('Filestore_db.ConnectorOut_sisconnprd39c','./FileStore/Filestore_db.ConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_db.ConnectorOut_sisconnprd39c','Filestore_db.ConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_db.ConnectorOut_sisconnprd40b','./FileStore/Filestore_db.ConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_db.ConnectorOut_sisconnprd40b','Filestore_db.ConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_db.ConnectorOut_sisconnprd41a','./FileStore/Filestore_db.ConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_db.ConnectorOut_sisconnprd41a','Filestore_db.ConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_db.ConnectorOut_sisconnprd41b','./FileStore/Filestore_db.ConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_db.ConnectorOut_sisconnprd41b','Filestore_db.ConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_db.ConnectorOut')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_db.ConnectorOut_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_db.ConnectorOut_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_db.ConnectorOut_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_db.ConnectorOut_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.db.ConnectorOutDLQ','sis.db.ConnectorOutDLQ','SubDeployment_db.ConnectorOut','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.db.ConnectorOutQueue','sis.db.ConnectorOutQueue','SubDeployment_db.ConnectorOut','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.db.ConnectorOutQueue','sis.db.ConnectorOutDLQ',30000,0)
CriarFileStore('Filestore_expediter.OnlineConnectorIn_sisconnprd39c','./FileStore/Filestore_expediter.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_expediter.OnlineConnectorIn_sisconnprd39c','Filestore_expediter.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_expediter.OnlineConnectorIn_sisconnprd40b','./FileStore/Filestore_expediter.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_expediter.OnlineConnectorIn_sisconnprd40b','Filestore_expediter.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_expediter.OnlineConnectorIn_sisconnprd41a','./FileStore/Filestore_expediter.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_expediter.OnlineConnectorIn_sisconnprd41a','Filestore_expediter.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_expediter.OnlineConnectorIn_sisconnprd41b','./FileStore/Filestore_expediter.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_expediter.OnlineConnectorIn_sisconnprd41b','Filestore_expediter.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_expediter.OnlineConnectorIn')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_expediter.OnlineConnectorIn_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_expediter.OnlineConnectorIn_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_expediter.OnlineConnectorIn_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_expediter.OnlineConnectorIn_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.expediter.OnlineConnectorInDLQ','sis.expediter.OnlineConnectorInDLQ','SubDeployment_expediter.OnlineConnectorIn','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.expediter.OnlineConnectorInQueue','sis.expediter.OnlineConnectorInQueue','SubDeployment_expediter.OnlineConnectorIn','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.expediter.OnlineConnectorInQueue','sis.expediter.OnlineConnectorInDLQ',30000,0)
CriarFileStore('Filestore_expediter.OnlineConnectorOut_sisconnprd39c','./FileStore/Filestore_expediter.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_expediter.OnlineConnectorOut_sisconnprd39c','Filestore_expediter.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_expediter.OnlineConnectorOut_sisconnprd40b','./FileStore/Filestore_expediter.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_expediter.OnlineConnectorOut_sisconnprd40b','Filestore_expediter.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_expediter.OnlineConnectorOut_sisconnprd41a','./FileStore/Filestore_expediter.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_expediter.OnlineConnectorOut_sisconnprd41a','Filestore_expediter.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_expediter.OnlineConnectorOut_sisconnprd41b','./FileStore/Filestore_expediter.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_expediter.OnlineConnectorOut_sisconnprd41b','Filestore_expediter.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_expediter.OnlineConnectorOut')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_expediter.OnlineConnectorOut_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_expediter.OnlineConnectorOut_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_expediter.OnlineConnectorOut_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_expediter.OnlineConnectorOut_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.expediter.OnlineConnectorOutDLQ','sis.expediter.OnlineConnectorOutDLQ','SubDeployment_expediter.OnlineConnectorOut','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.expediter.OnlineConnectorOutQueue','sis.expediter.OnlineConnectorOutQueue','SubDeployment_expediter.OnlineConnectorOut','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.expediter.OnlineConnectorOutQueue','sis.expediter.OnlineConnectorOutDLQ',30000,0)
CriarFileStore('Filestore_gos.OnlineConnectorIn_sisconnprd39c','./FileStore/Filestore_gos.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_gos.OnlineConnectorIn_sisconnprd39c','Filestore_gos.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_gos.OnlineConnectorIn_sisconnprd40b','./FileStore/Filestore_gos.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_gos.OnlineConnectorIn_sisconnprd40b','Filestore_gos.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_gos.OnlineConnectorIn_sisconnprd41a','./FileStore/Filestore_gos.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_gos.OnlineConnectorIn_sisconnprd41a','Filestore_gos.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_gos.OnlineConnectorIn_sisconnprd41b','./FileStore/Filestore_gos.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_gos.OnlineConnectorIn_sisconnprd41b','Filestore_gos.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_gos.OnlineConnectorIn')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_gos.OnlineConnectorIn_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_gos.OnlineConnectorIn_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_gos.OnlineConnectorIn_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_gos.OnlineConnectorIn_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.gos.OnlineConnectorInDLQ','sis.gos.OnlineConnectorInDLQ','SubDeployment_gos.OnlineConnectorIn','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.gos.OnlineConnectorInQueue','sis.gos.OnlineConnectorInQueue','SubDeployment_gos.OnlineConnectorIn','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.gos.OnlineConnectorInQueue','sis.gos.OnlineConnectorInDLQ',30000,0)
CriarFileStore('Filestore_gos.OnlineConnectorOut_sisconnprd39c','./FileStore/Filestore_gos.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_gos.OnlineConnectorOut_sisconnprd39c','Filestore_gos.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_gos.OnlineConnectorOut_sisconnprd40b','./FileStore/Filestore_gos.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_gos.OnlineConnectorOut_sisconnprd40b','Filestore_gos.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_gos.OnlineConnectorOut_sisconnprd41a','./FileStore/Filestore_gos.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_gos.OnlineConnectorOut_sisconnprd41a','Filestore_gos.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_gos.OnlineConnectorOut_sisconnprd41b','./FileStore/Filestore_gos.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_gos.OnlineConnectorOut_sisconnprd41b','Filestore_gos.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_gos.OnlineConnectorOut')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_gos.OnlineConnectorOut_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_gos.OnlineConnectorOut_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_gos.OnlineConnectorOut_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_gos.OnlineConnectorOut_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.gos.OnlineConnectorOutDLQ','sis.gos.OnlineConnectorOutDLQ','SubDeployment_gos.OnlineConnectorOut','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.gos.OnlineConnectorOutQueue','sis.gos.OnlineConnectorOutQueue','SubDeployment_gos.OnlineConnectorOut','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.gos.OnlineConnectorOutQueue','sis.gos.OnlineConnectorOutDLQ',30000,0)
CriarFileStore('Filestore_loader.OnlineConnectorIn_sisconnprd39c','./FileStore/Filestore_loader.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_loader.OnlineConnectorIn_sisconnprd39c','Filestore_loader.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_loader.OnlineConnectorIn_sisconnprd40b','./FileStore/Filestore_loader.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_loader.OnlineConnectorIn_sisconnprd40b','Filestore_loader.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_loader.OnlineConnectorIn_sisconnprd41a','./FileStore/Filestore_loader.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_loader.OnlineConnectorIn_sisconnprd41a','Filestore_loader.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_loader.OnlineConnectorIn_sisconnprd41b','./FileStore/Filestore_loader.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_loader.OnlineConnectorIn_sisconnprd41b','Filestore_loader.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_loader.OnlineConnectorIn')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_loader.OnlineConnectorIn_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_loader.OnlineConnectorIn_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_loader.OnlineConnectorIn_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_loader.OnlineConnectorIn_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.loader.OnlineConnectorInDLQ','sis.loader.OnlineConnectorInDLQ','SubDeployment_loader.OnlineConnectorIn','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.loader.OnlineConnectorInQueue','sis.loader.OnlineConnectorInQueue','SubDeployment_loader.OnlineConnectorIn','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.loader.OnlineConnectorInQueue','sis.loader.OnlineConnectorInDLQ',30000,0)
CriarFileStore('Filestore_loader.OnlineConnectorOut_sisconnprd39c','./FileStore/Filestore_loader.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_loader.OnlineConnectorOut_sisconnprd39c','Filestore_loader.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_loader.OnlineConnectorOut_sisconnprd40b','./FileStore/Filestore_loader.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_loader.OnlineConnectorOut_sisconnprd40b','Filestore_loader.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_loader.OnlineConnectorOut_sisconnprd41a','./FileStore/Filestore_loader.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_loader.OnlineConnectorOut_sisconnprd41a','Filestore_loader.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_loader.OnlineConnectorOut_sisconnprd41b','./FileStore/Filestore_loader.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_loader.OnlineConnectorOut_sisconnprd41b','Filestore_loader.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_loader.OnlineConnectorOut')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_loader.OnlineConnectorOut_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_loader.OnlineConnectorOut_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_loader.OnlineConnectorOut_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_loader.OnlineConnectorOut_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.loader.OnlineConnectorOutDLQ','sis.loader.OnlineConnectorOutDLQ','SubDeployment_loader.OnlineConnectorOut','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.loader.OnlineConnectorOutQueue','sis.loader.OnlineConnectorOutQueue','SubDeployment_loader.OnlineConnectorOut','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.loader.OnlineConnectorOutQueue','sis.loader.OnlineConnectorOutDLQ',30000,0)
CriarFileStore('Filestore_m2m.OnlineConnectorIn_sisconnprd39c','./FileStore/Filestore_m2m.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_m2m.OnlineConnectorIn_sisconnprd39c','Filestore_m2m.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_m2m.OnlineConnectorIn_sisconnprd40b','./FileStore/Filestore_m2m.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_m2m.OnlineConnectorIn_sisconnprd40b','Filestore_m2m.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_m2m.OnlineConnectorIn_sisconnprd41a','./FileStore/Filestore_m2m.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_m2m.OnlineConnectorIn_sisconnprd41a','Filestore_m2m.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_m2m.OnlineConnectorIn_sisconnprd41b','./FileStore/Filestore_m2m.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_m2m.OnlineConnectorIn_sisconnprd41b','Filestore_m2m.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_m2m.OnlineConnectorIn')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_m2m.OnlineConnectorIn_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_m2m.OnlineConnectorIn_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_m2m.OnlineConnectorIn_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_m2m.OnlineConnectorIn_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.m2m.OnlineConnectorInDLQ','sis.m2m.OnlineConnectorInDLQ','SubDeployment_m2m.OnlineConnectorIn','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.m2m.OnlineConnectorInQueue','sis.m2m.OnlineConnectorInQueue','SubDeployment_m2m.OnlineConnectorIn','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.m2m.OnlineConnectorInQueue','sis.m2m.OnlineConnectorInDLQ',30000,0)
CriarFileStore('Filestore_m2m.OnlineConnectorOut_sisconnprd39c','./FileStore/Filestore_m2m.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_m2m.OnlineConnectorOut_sisconnprd39c','Filestore_m2m.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_m2m.OnlineConnectorOut_sisconnprd40b','./FileStore/Filestore_m2m.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_m2m.OnlineConnectorOut_sisconnprd40b','Filestore_m2m.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_m2m.OnlineConnectorOut_sisconnprd41a','./FileStore/Filestore_m2m.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_m2m.OnlineConnectorOut_sisconnprd41a','Filestore_m2m.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_m2m.OnlineConnectorOut_sisconnprd41b','./FileStore/Filestore_m2m.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_m2m.OnlineConnectorOut_sisconnprd41b','Filestore_m2m.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_m2m.OnlineConnectorOut')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_m2m.OnlineConnectorOut_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_m2m.OnlineConnectorOut_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_m2m.OnlineConnectorOut_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_m2m.OnlineConnectorOut_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.m2m.OnlineConnectorOutDLQ','sis.m2m.OnlineConnectorOutDLQ','SubDeployment_m2m.OnlineConnectorOut','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.m2m.OnlineConnectorOutQueue','sis.m2m.OnlineConnectorOutQueue','SubDeployment_m2m.OnlineConnectorOut','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.m2m.OnlineConnectorOutQueue','sis.m2m.OnlineConnectorOutDLQ',30000,0)
CriarFileStore('Filestore_mesox.OnlineConnectorIn_sisconnprd39c','./FileStore/Filestore_mesox.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_mesox.OnlineConnectorIn_sisconnprd39c','Filestore_mesox.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_mesox.OnlineConnectorIn_sisconnprd40b','./FileStore/Filestore_mesox.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_mesox.OnlineConnectorIn_sisconnprd40b','Filestore_mesox.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_mesox.OnlineConnectorIn_sisconnprd41a','./FileStore/Filestore_mesox.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_mesox.OnlineConnectorIn_sisconnprd41a','Filestore_mesox.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_mesox.OnlineConnectorIn_sisconnprd41b','./FileStore/Filestore_mesox.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_mesox.OnlineConnectorIn_sisconnprd41b','Filestore_mesox.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_mesox.OnlineConnectorIn')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_mesox.OnlineConnectorIn_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_mesox.OnlineConnectorIn_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_mesox.OnlineConnectorIn_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_mesox.OnlineConnectorIn_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.mesox.OnlineConnectorInDLQ','sis.mesox.OnlineConnectorInDLQ','SubDeployment_mesox.OnlineConnectorIn','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.mesox.OnlineConnectorInQueue','sis.mesox.OnlineConnectorInQueue','SubDeployment_mesox.OnlineConnectorIn','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.mesox.OnlineConnectorInQueue','sis.mesox.OnlineConnectorInDLQ',30000,0)
CriarFileStore('Filestore_mesox.OnlineConnectorOut_sisconnprd39c','./FileStore/Filestore_mesox.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_mesox.OnlineConnectorOut_sisconnprd39c','Filestore_mesox.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_mesox.OnlineConnectorOut_sisconnprd40b','./FileStore/Filestore_mesox.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_mesox.OnlineConnectorOut_sisconnprd40b','Filestore_mesox.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_mesox.OnlineConnectorOut_sisconnprd41a','./FileStore/Filestore_mesox.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_mesox.OnlineConnectorOut_sisconnprd41a','Filestore_mesox.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_mesox.OnlineConnectorOut_sisconnprd41b','./FileStore/Filestore_mesox.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_mesox.OnlineConnectorOut_sisconnprd41b','Filestore_mesox.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_mesox.OnlineConnectorOut')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_mesox.OnlineConnectorOut_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_mesox.OnlineConnectorOut_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_mesox.OnlineConnectorOut_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_mesox.OnlineConnectorOut_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.mesox.OnlineConnectorOutDLQ','sis.mesox.OnlineConnectorOutDLQ','SubDeployment_mesox.OnlineConnectorOut','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.mesox.OnlineConnectorOutQueue','sis.mesox.OnlineConnectorOutQueue','SubDeployment_mesox.OnlineConnectorOut','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.mesox.OnlineConnectorOutQueue','sis.mesox.OnlineConnectorOutDLQ',30000,0)
CriarFileStore('Filestore_ogs.OnlineConnectorIn_sisconnprd39c','./FileStore/Filestore_ogs.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_ogs.OnlineConnectorIn_sisconnprd39c','Filestore_ogs.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_ogs.OnlineConnectorIn_sisconnprd40b','./FileStore/Filestore_ogs.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_ogs.OnlineConnectorIn_sisconnprd40b','Filestore_ogs.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_ogs.OnlineConnectorIn_sisconnprd41a','./FileStore/Filestore_ogs.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_ogs.OnlineConnectorIn_sisconnprd41a','Filestore_ogs.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_ogs.OnlineConnectorIn_sisconnprd41b','./FileStore/Filestore_ogs.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_ogs.OnlineConnectorIn_sisconnprd41b','Filestore_ogs.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_ogs.OnlineConnectorIn')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_ogs.OnlineConnectorIn_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ogs.OnlineConnectorIn_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ogs.OnlineConnectorIn_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ogs.OnlineConnectorIn_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.ogs.OnlineConnectorInDLQ','sis.ogs.OnlineConnectorInDLQ','SubDeployment_ogs.OnlineConnectorIn','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.ogs.OnlineConnectorInQueue','sis.ogs.OnlineConnectorInQueue','SubDeployment_ogs.OnlineConnectorIn','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.ogs.OnlineConnectorInQueue','sis.ogs.OnlineConnectorInDLQ',30000,0)
CriarFileStore('Filestore_ogs.OnlineConnectorOut_sisconnprd39c','./FileStore/Filestore_ogs.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_ogs.OnlineConnectorOut_sisconnprd39c','Filestore_ogs.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_ogs.OnlineConnectorOut_sisconnprd40b','./FileStore/Filestore_ogs.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_ogs.OnlineConnectorOut_sisconnprd40b','Filestore_ogs.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_ogs.OnlineConnectorOut_sisconnprd41a','./FileStore/Filestore_ogs.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_ogs.OnlineConnectorOut_sisconnprd41a','Filestore_ogs.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_ogs.OnlineConnectorOut_sisconnprd41b','./FileStore/Filestore_ogs.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_ogs.OnlineConnectorOut_sisconnprd41b','Filestore_ogs.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_ogs.OnlineConnectorOut')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_ogs.OnlineConnectorOut_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ogs.OnlineConnectorOut_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ogs.OnlineConnectorOut_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ogs.OnlineConnectorOut_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.ogs.OnlineConnectorOutDLQ','sis.ogs.OnlineConnectorOutDLQ','SubDeployment_ogs.OnlineConnectorOut','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.ogs.OnlineConnectorOutQueue','sis.ogs.OnlineConnectorOutQueue','SubDeployment_ogs.OnlineConnectorOut','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.ogs.OnlineConnectorOutQueue','sis.ogs.OnlineConnectorOutDLQ',30000,0)
CriarFileStore('Filestore_soa.OnlineConnectorIn_sisconnprd39c','./FileStore/Filestore_soa.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_soa.OnlineConnectorIn_sisconnprd39c','Filestore_soa.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_soa.OnlineConnectorIn_sisconnprd40b','./FileStore/Filestore_soa.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_soa.OnlineConnectorIn_sisconnprd40b','Filestore_soa.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_soa.OnlineConnectorIn_sisconnprd41a','./FileStore/Filestore_soa.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_soa.OnlineConnectorIn_sisconnprd41a','Filestore_soa.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_soa.OnlineConnectorIn_sisconnprd41b','./FileStore/Filestore_soa.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_soa.OnlineConnectorIn_sisconnprd41b','Filestore_soa.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_soa.OnlineConnectorIn')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_soa.OnlineConnectorIn_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_soa.OnlineConnectorIn_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_soa.OnlineConnectorIn_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_soa.OnlineConnectorIn_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.soa.OnlineConnectorInDLQ','sis.soa.OnlineConnectorInDLQ','SubDeployment_soa.OnlineConnectorIn','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.soa.OnlineConnectorInQueue','sis.soa.OnlineConnectorInQueue','SubDeployment_soa.OnlineConnectorIn','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.soa.OnlineConnectorInQueue','sis.soa.OnlineConnectorInDLQ',30000,0)
CriarFileStore('Filestore_soa.OnlineConnectorOut_sisconnprd39c','./FileStore/Filestore_soa.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_soa.OnlineConnectorOut_sisconnprd39c','Filestore_soa.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_soa.OnlineConnectorOut_sisconnprd40b','./FileStore/Filestore_soa.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_soa.OnlineConnectorOut_sisconnprd40b','Filestore_soa.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_soa.OnlineConnectorOut_sisconnprd41a','./FileStore/Filestore_soa.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_soa.OnlineConnectorOut_sisconnprd41a','Filestore_soa.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_soa.OnlineConnectorOut_sisconnprd41b','./FileStore/Filestore_soa.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_soa.OnlineConnectorOut_sisconnprd41b','Filestore_soa.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_soa.OnlineConnectorOut')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_soa.OnlineConnectorOut_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_soa.OnlineConnectorOut_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_soa.OnlineConnectorOut_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_soa.OnlineConnectorOut_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.soa.OnlineConnectorOutDLQ','sis.soa.OnlineConnectorOutDLQ','SubDeployment_soa.OnlineConnectorOut','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.soa.OnlineConnectorOutQueue','sis.soa.OnlineConnectorOutQueue','SubDeployment_soa.OnlineConnectorOut','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.soa.OnlineConnectorOutQueue','sis.soa.OnlineConnectorOutDLQ',30000,0)
CriarFileStore('Filestore_som.OnlineConnectorIn_sisconnprd39c','./FileStore/Filestore_som.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_som.OnlineConnectorIn_sisconnprd39c','Filestore_som.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_som.OnlineConnectorIn_sisconnprd40b','./FileStore/Filestore_som.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_som.OnlineConnectorIn_sisconnprd40b','Filestore_som.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_som.OnlineConnectorIn_sisconnprd41a','./FileStore/Filestore_som.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_som.OnlineConnectorIn_sisconnprd41a','Filestore_som.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_som.OnlineConnectorIn_sisconnprd41b','./FileStore/Filestore_som.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_som.OnlineConnectorIn_sisconnprd41b','Filestore_som.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_som.OnlineConnectorIn')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_som.OnlineConnectorIn_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_som.OnlineConnectorIn_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_som.OnlineConnectorIn_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_som.OnlineConnectorIn_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.som.OnlineConnectorInDLQ','sis.som.OnlineConnectorInDLQ','SubDeployment_som.OnlineConnectorIn','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.som.OnlineConnectorInQueue','sis.som.OnlineConnectorInQueue','SubDeployment_som.OnlineConnectorIn','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.som.OnlineConnectorInQueue','sis.som.OnlineConnectorInDLQ',30000,0)
CriarFileStore('Filestore_som.OnlineConnectorOut_sisconnprd39c','./FileStore/Filestore_som.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_som.OnlineConnectorOut_sisconnprd39c','Filestore_som.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_som.OnlineConnectorOut_sisconnprd40b','./FileStore/Filestore_som.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_som.OnlineConnectorOut_sisconnprd40b','Filestore_som.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_som.OnlineConnectorOut_sisconnprd41a','./FileStore/Filestore_som.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_som.OnlineConnectorOut_sisconnprd41a','Filestore_som.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_som.OnlineConnectorOut_sisconnprd41b','./FileStore/Filestore_som.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_som.OnlineConnectorOut_sisconnprd41b','Filestore_som.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_som.OnlineConnectorOut')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_som.OnlineConnectorOut_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_som.OnlineConnectorOut_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_som.OnlineConnectorOut_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_som.OnlineConnectorOut_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.som.OnlineConnectorOutDLQ','sis.som.OnlineConnectorOutDLQ','SubDeployment_som.OnlineConnectorOut','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.som.OnlineConnectorOutQueue','sis.som.OnlineConnectorOutQueue','SubDeployment_som.OnlineConnectorOut','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.som.OnlineConnectorOutQueue','sis.som.OnlineConnectorOutDLQ',30000,0)
CriarFileStore('Filestore_wli.OnlineConnectorIn_sisconnprd39c','./FileStore/Filestore_wli.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_wli.OnlineConnectorIn_sisconnprd39c','Filestore_wli.OnlineConnectorIn_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_wli.OnlineConnectorIn_sisconnprd40b','./FileStore/Filestore_wli.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_wli.OnlineConnectorIn_sisconnprd40b','Filestore_wli.OnlineConnectorIn_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_wli.OnlineConnectorIn_sisconnprd41a','./FileStore/Filestore_wli.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_wli.OnlineConnectorIn_sisconnprd41a','Filestore_wli.OnlineConnectorIn_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_wli.OnlineConnectorIn_sisconnprd41b','./FileStore/Filestore_wli.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_wli.OnlineConnectorIn_sisconnprd41b','Filestore_wli.OnlineConnectorIn_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_wli.OnlineConnectorIn')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_wli.OnlineConnectorIn_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_wli.OnlineConnectorIn_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_wli.OnlineConnectorIn_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_wli.OnlineConnectorIn_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.wli.OnlineConnectorInDLQ','sis.wli.OnlineConnectorInDLQ','SubDeployment_wli.OnlineConnectorIn','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.wli.OnlineConnectorInQueue','sis.wli.OnlineConnectorInQueue','SubDeployment_wli.OnlineConnectorIn','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.wli.OnlineConnectorInQueue','sis.wli.OnlineConnectorInDLQ',30000,0)
CriarFileStore('Filestore_wli.OnlineConnectorOut_sisconnprd39c','./FileStore/Filestore_wli.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_wli.OnlineConnectorOut_sisconnprd39c','Filestore_wli.OnlineConnectorOut_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_wli.OnlineConnectorOut_sisconnprd40b','./FileStore/Filestore_wli.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_wli.OnlineConnectorOut_sisconnprd40b','Filestore_wli.OnlineConnectorOut_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_wli.OnlineConnectorOut_sisconnprd41a','./FileStore/Filestore_wli.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_wli.OnlineConnectorOut_sisconnprd41a','Filestore_wli.OnlineConnectorOut_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_wli.OnlineConnectorOut_sisconnprd41b','./FileStore/Filestore_wli.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_wli.OnlineConnectorOut_sisconnprd41b','Filestore_wli.OnlineConnectorOut_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_wli.OnlineConnectorOut')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_wli.OnlineConnectorOut_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_wli.OnlineConnectorOut_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_wli.OnlineConnectorOut_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_wli.OnlineConnectorOut_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.wli.OnlineConnectorOutDLQ','sis.wli.OnlineConnectorOutDLQ','SubDeployment_wli.OnlineConnectorOut','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.wli.OnlineConnectorOutQueue','sis.wli.OnlineConnectorOutQueue','SubDeployment_wli.OnlineConnectorOut','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.wli.OnlineConnectorOutQueue','sis.wli.OnlineConnectorOutDLQ',30000,0)
CriarFileStore('Filestore_ProvisionerIn_sisconnprd39c','./FileStore/Filestore_ProvisionerIn_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_ProvisionerIn_sisconnprd39c','Filestore_ProvisionerIn_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_ProvisionerIn_sisconnprd40b','./FileStore/Filestore_ProvisionerIn_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_ProvisionerIn_sisconnprd40b','Filestore_ProvisionerIn_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_ProvisionerIn_sisconnprd41a','./FileStore/Filestore_ProvisionerIn_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_ProvisionerIn_sisconnprd41a','Filestore_ProvisionerIn_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_ProvisionerIn_sisconnprd41b','./FileStore/Filestore_ProvisionerIn_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_ProvisionerIn_sisconnprd41b','Filestore_ProvisionerIn_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_ProvisionerIn')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_ProvisionerIn_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerIn_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerIn_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerIn_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerInDLQ','sis.ProvisionerInDLQ','SubDeployment_ProvisionerIn','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerInQueue','sis.ProvisionerInQueue','SubDeployment_ProvisionerIn','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.ProvisionerInQueue','sis.ProvisionerInDLQ',30000,0)
CriarFileStore('Filestore_ProvisionerOut_sisconnprd39c','./FileStore/Filestore_ProvisionerOut_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_ProvisionerOut_sisconnprd39c','Filestore_ProvisionerOut_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_ProvisionerOut_sisconnprd40b','./FileStore/Filestore_ProvisionerOut_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_ProvisionerOut_sisconnprd40b','Filestore_ProvisionerOut_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_ProvisionerOut_sisconnprd41a','./FileStore/Filestore_ProvisionerOut_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_ProvisionerOut_sisconnprd41a','Filestore_ProvisionerOut_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_ProvisionerOut_sisconnprd41b','./FileStore/Filestore_ProvisionerOut_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_ProvisionerOut_sisconnprd41b','Filestore_ProvisionerOut_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_ProvisionerOut')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_ProvisionerOut_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerOut_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerOut_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerOut_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerOutDLQ','sis.ProvisionerOutDLQ','SubDeployment_ProvisionerOut','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerOutQueue','sis.ProvisionerOutQueue','SubDeployment_ProvisionerOut','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.ProvisionerOutQueue','sis.ProvisionerOutDLQ',30000,0)
CriarFileStore('Filestore_EventHistory_sisconnprd39c','./FileStore/Filestore_EventHistory_sisconnprd39c','sisconnprd39c','Server')
CriarJmsServer('JMSServer_EventHistory_sisconnprd39c','Filestore_EventHistory_sisconnprd39c','sisconnprd39c','Server')
CriarFileStore('Filestore_EventHistory_sisconnprd40b','./FileStore/Filestore_EventHistory_sisconnprd40b','sisconnprd40b','Server')
CriarJmsServer('JMSServer_EventHistory_sisconnprd40b','Filestore_EventHistory_sisconnprd40b','sisconnprd40b','Server')
CriarFileStore('Filestore_EventHistory_sisconnprd41a','./FileStore/Filestore_EventHistory_sisconnprd41a','sisconnprd41a','Server')
CriarJmsServer('JMSServer_EventHistory_sisconnprd41a','Filestore_EventHistory_sisconnprd41a','sisconnprd41a','Server')
CriarFileStore('Filestore_EventHistory_sisconnprd41b','./FileStore/Filestore_EventHistory_sisconnprd41b','sisconnprd41b','Server')
CriarJmsServer('JMSServer_EventHistory_sisconnprd41b','Filestore_EventHistory_sisconnprd41b','sisconnprd41b','Server')
CriarSubDeployment('sismodule','SubDeployment_EventHistory')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_EventHistory_sisconnprd39c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_EventHistory_sisconnprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_EventHistory_sisconnprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_EventHistory_sisconnprd41b,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.EventHistoryDLQ','sis.EventHistoryDLQ','SubDeployment_EventHistory','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.EventHistoryQueue','sis.EventHistoryQueue','SubDeployment_EventHistory','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.EventHistoryQueue','sis.EventHistoryDLQ',30000,0)
CriarFileStore('Filestore_ProvisionerInDB_sisconnprd39b','./FileStore/Filestore_ProvisionerInDB_sisconnprd39b','sisconnprd39b','Server')
CriarJmsServer('JMSServer_ProvisionerInDB_sisconnprd39b','Filestore_ProvisionerInDB_sisconnprd39b','sisconnprd39b','Server')
CriarFileStore('Filestore_ProvisionerInDB_sisconnprd40a','./FileStore/Filestore_ProvisionerInDB_sisconnprd40a','sisconnprd40a','Server')
CriarJmsServer('JMSServer_ProvisionerInDB_sisconnprd40a','Filestore_ProvisionerInDB_sisconnprd40a','sisconnprd40a','Server')
CriarSubDeployment('sismodule','SubDeployment_ProvisionerInDB')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_ProvisionerInDB_sisconnprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerInDB_sisconnprd40a,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerInDBDLQ','sis.ProvisionerInDBDLQ','SubDeployment_ProvisionerInDB','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerInDBQueue','sis.ProvisionerInQueue','SubDeployment_ProvisionerInDB','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.ProvisionerInDBQueue','sis.ProvisionerInDBDLQ',30000,0)
CriarFileStore('Filestore_ProvisionerOutDB_sisconnprd39b','./FileStore/Filestore_ProvisionerOutDB_sisconnprd39b','sisconnprd39b','Server')
CriarJmsServer('JMSServer_ProvisionerOutDB_sisconnprd39b','Filestore_ProvisionerOutDB_sisconnprd39b','sisconnprd39b','Server')
CriarFileStore('Filestore_ProvisionerOutDB_sisconnprd40a','./FileStore/Filestore_ProvisionerOutDB_sisconnprd40a','sisconnprd40a','Server')
CriarJmsServer('JMSServer_ProvisionerOutDB_sisconnprd40a','Filestore_ProvisionerOutDB_sisconnprd40a','sisconnprd40a','Server')
CriarSubDeployment('sismodule','SubDeployment_ProvisionerOutDB')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_ProvisionerOutDB_sisconnprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerOutDB_sisconnprd40a,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerOutDBDLQ','sis.ProvisionerOutDBDLQ','SubDeployment_ProvisionerOutDB','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerOutDBQueue','sis.ProvisionerOutQueue','SubDeployment_ProvisionerOutDB','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.ProvisionerOutDBQueue','sis.ProvisionerOutDBDLQ',30000,0)
CriarFileStore('Filestore_EventHistoryDB_sisconnprd39b','./FileStore/Filestore_EventHistoryDB_sisconnprd39b','sisconnprd39b','Server')
CriarJmsServer('JMSServer_EventHistoryDB_sisconnprd39b','Filestore_EventHistoryDB_sisconnprd39b','sisconnprd39b','Server')
CriarFileStore('Filestore_EventHistoryDB_sisconnprd40a','./FileStore/Filestore_EventHistoryDB_sisconnprd40a','sisconnprd40a','Server')
CriarJmsServer('JMSServer_EventHistoryDB_sisconnprd40a','Filestore_EventHistoryDB_sisconnprd40a','sisconnprd40a','Server')
CriarSubDeployment('sismodule','SubDeployment_EventHistoryDB')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_EventHistoryDB_sisconnprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_EventHistoryDB_sisconnprd40a,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.EventHistoryDBDLQ','sis.EventHistoryDBDLQ','SubDeployment_EventHistoryDB','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.EventHistoryDBQueue','sis.EventHistoryQueue','SubDeployment_EventHistoryDB','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.EventHistoryDBQueue','sis.EventHistoryDBDLQ',30000,0)
CriarBridgeTarget('ProvisionerInOri','eis.jms.WLSConnectionFactoryJNDIXA','sis.JMSConnectionFactory','t3://msisprd39:27007,msisprd40:27005,msisprd41:27003,msisprd41:27005,msisprd39:27005,msisprd40:27003','weblogic','welcome1','sis.ProvisionerInQueue')
CriarBridgeTarget('ProvisionerInDest','eis.jms.WLSConnectionFactoryJNDIXA','sis.JMSConnectionFactory','t3://msisprd39:57003,msisprd39:57005,msisprd40:57003,msisprd40:57005,msisprd40:57007,msisprd40:57009,msisprd41:57003,msisprd41:57005,msisprd41:57007','weblogic','welcome1','sis.ProvisionerInQueue')
CriarBridge('ProvisionerInBridge','Exactly-once','true','null','ProvisionerInOri','ProvisionerInDest','true')
set('Targets',jarray.array([ObjectName('com.bea:Name=sisconnectorprd,Type=Cluster'),ObjectName('com.bea:Name=sisconnectorbdprd,Type=Cluster')], ObjectName))
CriarBridgeTarget('ProvisionerOutOri','eis.jms.WLSConnectionFactoryJNDIXA','sis.JMSConnectionFactory','t3://msisprd39:57003,msisprd39:57005,msisprd40:57003,msisprd40:57005,msisprd40:57007,msisprd40:57009,msisprd41:57003,msisprd41:57005,msisprd41:57007','weblogic','welcome1','sis.ProvisionerOutQueue')
CriarBridgeTarget('ProvisionerOutDest','eis.jms.WLSConnectionFactoryJNDIXA','sis.JMSConnectionFactory','t3://msisprd39:27007,msisprd40:27005,msisprd41:27003,msisprd41:27005','weblogic','welcome1','sis.ProvisionerOutQueue')
CriarBridge('ProvisionerOutBridge','Exactly-once','true','CONNECTOR_NAME <> dbconnector','ProvisionerOutOri','ProvisionerOutDest','true')
set('Targets',jarray.array([ObjectName('com.bea:Name=sisconnectorprd,Type=Cluster')], ObjectName))
CriarBridgeTarget('ProvisionerOutDBOri','eis.jms.WLSConnectionFactoryJNDIXA','sis.JMSConnectionFactory','t3://msisprd39:57003,msisprd39:57005,msisprd40:57003,msisprd40:57005,msisprd40:57007,msisprd40:57009,msisprd41:57003,msisprd41:57005,msisprd41:57007','weblogic','welcome1','sis.ProvisionerOutQueue')
CriarBridgeTarget('ProvisionerOutDBDest','eis.jms.WLSConnectionFactoryJNDIXA','sis.JMSConnectionFactory','t3://msisprd39:27005,msisprd40:27003','weblogic','welcome1','sis.ProvisionerOutQueue')
CriarBridge('ProvisionerOutDBBridge','Exactly-once','true','CONNECTOR_NAME = dbconnector','ProvisionerOutDBOri','ProvisionerOutDBDest','true')
set('Targets',jarray.array([ObjectName('com.bea:Name=sisconnectorprd,Type=Cluster')], ObjectName))
CriarBridgeTarget('EventHistoryOri','eis.jms.WLSConnectionFactoryJNDIXA','sis.JMSConnectionFactory','t3://msisprd39:27007,msisprd40:27005,msisprd41:27003,msisprd41:27005,msisprd39:27005,msisprd40:27003','weblogic','welcome1','sis.EventHistoryQueue')
CriarBridgeTarget('EventHistoryDest','eis.jms.WLSConnectionFactoryJNDIXA','sis.JMSConnectionFactory','t3://msisprd38:37005,msisprd38:37007,msisprd38:37009,msisprd39:37003,msisprd39:37005,msisprd39:37007,msisprd40:37003,msisprd40:37003','weblogic','welcome1','sis.EventHistoryQueue')
CriarBridge('EventHistoryBridge','Exactly-once','true','null','EventHistoryOri','EventHistoryDest','true')
set('Targets',jarray.array([ObjectName('com.bea:Name=sisconnectorprd,Type=Cluster'),ObjectName('com.bea:Name=sisconnectorbdprd,Type=Cluster')], ObjectName))
save()
activate()
exit()
