def CriarJdbcStore(name, prefixName, target, dataSource):
	print ('Criando JdbcStore: ' + name )
	cd('/')
	create(name,'JdbcStore')
	cd('JdbcStore/'+name)
	set('PrefixName',prefixName)
	set('Target',target)
	DataSource('Target',dataSource)

def CriarFila(type, moduleName, name, jndiName, subdeployment, priorityDestinationKey):
	print ('Criando Fila: ' + name )
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/'+ moduleName)
	if (type == 'QUEUE'):
		myq=create(name,'Queue')
	else:
		myq=create(name,'UniformDistributedQueue')
	myq.setJNDIName(jndiName)
	myq.setSubDeploymentName(subdeployment)
	if (priorityDestinationKey != 'null'):
		myq.setDestinationKeys(jarray.array([String(priorityDestinationKey)],String))

def CriarDeliveryfailure(moduleName, type, queueName, destinationKey, redeliveryDelay, redeliveryLimit):
	print ('Criando Deliveryfailure para a fila: ' + queueName )
	if (type == 'QUEUE'):
		cd('Queues/' + queueName)
		cmo = cd('DeliveryFailureParams/' + queueName)
		cmo.setRedeliveryLimit(redeliveryLimit)
		cmo.setExpirationPolicy('Redirect')
		
		cmo.setErrorDestination(getMBean('/JMSSystemResources/'+moduleName+'/JMSResource/'+moduleName+'/Queues/'+destinationKey))
		cd('..')
		cd('..')
		cmo = cd('DeliveryParamsOverrides/' + queueName)
		cmo.setRedeliveryDelay(redeliveryDelay)
	else:
		cd('UniformDistributedQueues/' + queueName)
		cmo = cd('DeliveryFailureParams/' + queueName)
		cmo.setRedeliveryLimit(redeliveryLimit)
		cmo.setExpirationPolicy('Redirect')
		print ('cmo.setErrorDestination(getMBean(''/JMSSystemResources/'+moduleName+'/JMSResource/'+moduleName+'/UniformDistributedQueues/'+destinationKey+'))')
		cmo.setErrorDestination(getMBean('/JMSSystemResources/'+moduleName+'/JMSResource/'+moduleName+'/UniformDistributedQueues/'+destinationKey))
		cd('..')
		cd('..')
		cmo = cd('DeliveryParamsOverrides/' + queueName)
		cmo.setRedeliveryDelay(redeliveryDelay)
	

def CriarAdminServer(name, port, sslPort):
	print ('Criando AdminServer: ' + name )
	cd('Servers/'+name)
	set('ListenPort',port)
	cd('SSL/AdminServer')
	set('Enabled','True')
	set('ListenPort',sslPort)

def CriarCluster(name, multicastAddress, port, address):
	print ('Criando Cluster: ' + name )
	cd('/')
	create(name,'Cluster')
	cd('Clusters/'+name)
	if (multicastAddress != 'null'):
		set('MulticastAddress',multicastAddress)
	if (port != 0):
		set('MulticastPort',port)
	if (address != 'null'):
		set('ClusterAddress',address)

def CriarFileStore(name, path, target, targetType):
	print ('Criando FileStore: ' + name )
	cd('/')
	create(name,'FileStore')
	cd('FileStores/'+name)
	set('Directory',path)
	set('Targets',jarray.array([ObjectName('com.bea:Name='+target+',Type='+targetType)], ObjectName))

def CriarJmsServer(name, persistentStore, target, targetType):
	print ('Criando JmsServer: ' + name )
	cd('/')
	create(name,'JMSServer')
	cd('JMSServers/'+name)
	set('PersistentStore',ObjectName('com.bea:Name='+persistentStore+',Type=FileStore'))
	set('Targets',jarray.array([ObjectName('com.bea:Name='+target+',Type='+targetType)], ObjectName))

def CriarTopic(moduleName, name, subdeployment, redeliveryDelay, redeliveryLimit):
	print ('Criando Topic: ' + name )
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/' + moduleName)
	top=create(name,'Topic')
	top.setJNDIName(name)
	top.setSubDeploymentName(subdeployment)
	cd('Topics/' + name)
	cd('DeliveryFailureParams/' + name)
	set('RedeliveryLimit',redeliveryLimit)
	cd('..')
	cd('..')
	cd('DeliveryParamsOverrides/' + name)
	set('RedeliveryDelay', redeliveryDelay)

def CriarPriorityDestinationKey(moduleName, name, sortKey, keyType, direction):
	print ('Criando Priority Destination Key: ' + name )
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/' + moduleName)
	create(name,'DestinationKey')
	cd('DestinationKeys/' + name)
	set('Property',sortKey)
	set('KeyType',keyType)
	set('SortOrder',direction)

def CriarManagedServer(name, port, address, machine, cluster):
	print ('Criando Managed Server: ' + name )
	cd('/')
	create(name,'Server')
	cd('Servers/' + name)
	set('ListenPort',port)
	if (cluster != 'null'):
		cmo.setMachine (getMBean('/Machines/' + machine))
	set('ListenAddress',address)
	if (cluster != 'null'):
		cmo.setCluster (getMBean('/Clusters/' + cluster))

def CriarDatasource(jndiName):
	print ('Criando Datasource: ' + jndiName )
	cd('/')
	varDataSource=create(jndiName,'JDBCSystemResource')
	cd('JDBCSystemResources/' + jndiName + '/JDBCResource/' + jndiName)
	set('Name',jndiName)

def CriarJmsModule(name):
	print ('Criando JmsModulo: ' + name )
	cd('/')
	create(name,'JMSSystemResource')
	cd('JMSSystemResources/' + name)

def CriarConnectionfactory(moduleName, name, jndiName, reconnectPolicy, maxMessagesPerSession, isServerAffinityEnabled, isXAConnectionFactoryEnabled, sendTimeout):
	print ('Criando Connection Factory: ' + name )
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/' + moduleName)
	create(name,'ConnectionFactory')
	cd('ConnectionFactories/' + jndiName)
	set('JNDIName',jndiName)
	set('DefaultTargetingEnabled','true')
	cd('ClientParams/' + jndiName)
	set('ReconnectPolicy',reconnectPolicy)
	set('MessagesMaximum',maxMessagesPerSession)
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/' + moduleName)
	cd('ConnectionFactories/' + jndiName)
	cd('LoadBalancingParams/' + jndiName)
	set('ServerAffinityEnabled',isServerAffinityEnabled)
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/' + moduleName)
	cd('ConnectionFactories/' + jndiName)
	cd('TransactionParams/' + jndiName)
	set('XAConnectionFactoryEnabled',isXAConnectionFactoryEnabled)
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/' + moduleName)
	cd('ConnectionFactories/' + jndiName)
	cd('DefaultDeliveryParams/' + jndiName)
	set('SendTimeout',sendTimeout)

def CriarConnectionPool(datasourceName, driverClassName, url, dbPassword, dbUsername, inCapacity, maxCapacity, incrementCapacity, isTestConnReserve, testTableName, shrinkFrequency, connCreationRetryFrequency, incativeConnectionTimeoutSeconds, connReserveTimeout, maxCapacityInit, minCapacityInit, statementCache, testFrequency, supportsGlobal):
	print ('Criando Connection Pool para datasource: ' + datasourceName )
	cd('JDBCDriverParams/' + datasourceName)
	set('DriverName',driverClassName)
	set('Url',url)
	set('PasswordEncrypted',dbPassword)
	cd('Properties/' + datasourceName)
	create('user','Property')
	cd('Properties/user')
	cmo.setValue(dbUsername)
	cd('/JDBCSystemResources/' + datasourceName + '/JDBCResource/' + datasourceName)
	cd('JDBCDataSourceParams/' + datasourceName)
	set('JNDINames',jarray.array([String(datasourceName)], String))
	if (supportsGlobal == 'true'):
		set('GlobalTransactionsProtocol', java.lang.String('None'))
	else:
		set('GlobalTransactionsProtocol', java.lang.String('LoggingLastResource'))
	cd('/JDBCSystemResources/' + datasourceName + '/JDBCResource/' + datasourceName)
	cd('JDBCConnectionPoolParams/' + datasourceName)
	set('InitialCapacity',inCapacity)
	set('MaxCapacity',maxCapacity)
	set('MinCapacity',minCapacityInit)
	set('StatementCacheSize',statementCache)
	set('TestFrequencySeconds',testFrequency)
	set('HighestNumWaiters',maxCapacity)
	set('CapacityIncrement',incrementCapacity)
	set('TestConnectionsOnReserve',isTestConnReserve)
	set('TestTableName',testTableName)
	set('ShrinkFrequencySeconds',shrinkFrequency)
	set('ConnectionCreationRetryFrequencySeconds',connCreationRetryFrequency)
	if (incativeConnectionTimeoutSeconds != 0):
		set('InactiveConnectionTimeoutSeconds',incativeConnectionTimeoutSeconds)
	set('ConnectionReserveTimeoutSeconds',connReserveTimeout)
	if(datasourceName == 'sis.TempDataSource'):
		cd('/JDBCSystemResources/'+datasourceName+'/JDBCResource/'+datasourceName+'/JDBCXAParams/'+datasourceName)
		set('XaSetTransactionTimeout', 'true')
		cmo.setXaTransactionTimeout(600)

def CriarSubDeployment(name, subName):
	print ('Criando SubDeployment: ' + name )
	cd('/')
	cd('JMSSystemResources/' + name)
	create(subName,'SubDeployment')
	cd('SubDeployments/' + subName)

def CriarTemplate(moduleName, templateName, templateDestinationKey):
	print ('Criando Template: ' + moduleName )
	cd('/')
	cd('JMSSystemResources/' + moduleName + '/JMSResource/'+ moduleName)
	create(templateName,'Template')
	cd('Templates/' + templateName)
	set('DestinationKeys',jarray.array([String(templateDestinationKey)], String))

def CriarWorkManager(workManagerName, domainName):
	print ('Criando WorkManager: ' + workManagerName )
	cd('/')
	name = get('Name')
	cd('SelfTuning/' + name)
	create(workManagerName,'WorkManager')
	cd('WorkManagers/' + workManagerName)
	cmo.setMinThreadsConstraint(getMBean('/SelfTuning/' + name + '/MinThreadsConstraints/' + workManagerName + 'MinThreads'))
	cmo.setMaxThreadsConstraint(getMBean('/SelfTuning/' + name + '/MaxThreadsConstraints/' + workManagerName + 'MaxThreads'))

def CriarWorkManagerMinThread(workManagerName, domainName, minCount):
	print ('Criando WorkManager: ' + workManagerName + 'MinThreads' )
	cd('/')
	name = get('Name')
	cd('SelfTuning/' + name)
	create(workManagerName+'MinThreads','MinThreadsConstraint')
	cd('MinThreadsConstraints/' + workManagerName+'MinThreads')
	cmo.setCount(int(minCount))

def CriarWorkManagerMaxThread(workManagerName, domainName, maxCount):
	print ('Criando WorkManager: ' + workManagerName + 'MaxThreads' )
	cd('/')
	name = get('Name')
	cd('SelfTuning/' + name)
	create(workManagerName+'MaxThreads','MaxThreadsConstraint')
	cd('MaxThreadsConstraints/' + workManagerName+'MaxThreads')
	cmo.setCount(int(maxCount))

def CriarBridgeTarget(name, adapterJNDIName, connectionFactoryJNDIName, connectionURL, userName, userPassword, destinationJNDIName):
	print ('Criando CriarBridgeTarget: ' + name )
	cd('/')
	cd('JMSBridgeDestinations')
	create(name)
	cd(name)
	set('AdapterJNDIName', adapterJNDIName)
	set('ConnectionFactoryJNDIName', connectionFactoryJNDIName)
	set('ConnectionURL', connectionURL)
	set('DestinationJNDIName', destinationJNDIName)
	if (userName != 'null'):
		set('UserName', userName)
	if (userPassword != 'null'):
		set('UserPassword', userPassword)

def CriarBridge(name, qualityOfService, started, selector, targetOri, targetDest, preserveMsgProperty):
	print ('Criando CriarBridge: ' + name )
	cd('/')
	cd('MessagingBridges')
	create(name)
	cd(name)
	set('QualityOfService', qualityOfService)
	set('Started', started)
	if (selector != 'null'):
		set('Selector', selector)
	set('PreserveMsgProperty', preserveMsgProperty)
	cmo.setSourceDestination(getMBean('/JMSBridgeDestinations/' + targetOri))
	cmo.setTargetDestination(getMBean('/JMSBridgeDestinations/' + targetDest))

connect('LOGIN', 'SENHA', 'msisprd41:57001')
edit()
startEdit()
CriarJmsModule('sisprovisioningmodule')
cd('/')
cd('JMSSystemResources/sisprovisioningmodule')
set('Targets',jarray.array([ObjectName('com.bea:Name=sisprovprd40a_sup,Type=Server'),ObjectName('com.bea:Name=sisprovisioningprd,Type=Cluster')], ObjectName))
CriarPriorityDestinationKey('sisprovisioningmodule','PriorityDestinationKey','JMSPriority','Long','Descending')
CriarFileStore('Filestore_Mno_sisprovprd39a','./FileStore/Filestore_Mno_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_Mno_sisprovprd39a','Filestore_Mno_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_Mno_sisprovprd39b','./FileStore/Filestore_Mno_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_Mno_sisprovprd39b','Filestore_Mno_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_Mno_sisprovprd40b','./FileStore/Filestore_Mno_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_Mno_sisprovprd40b','Filestore_Mno_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_Mno_sisprovprd40c','./FileStore/Filestore_Mno_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_Mno_sisprovprd40c','Filestore_Mno_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_Mno_sisprovprd40d','./FileStore/Filestore_Mno_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_Mno_sisprovprd40d','Filestore_Mno_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_Mno_sisprovprd41a','./FileStore/Filestore_Mno_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_Mno_sisprovprd41a','Filestore_Mno_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_Mno_sisprovprd41b','./FileStore/Filestore_Mno_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_Mno_sisprovprd41b','Filestore_Mno_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_Mno_sisprovprd41c','./FileStore/Filestore_Mno_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_Mno_sisprovprd41c','Filestore_Mno_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sisprovisioningmodule','SubDeployment_Mno')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_Mno_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_Mno_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_Mno_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_Mno_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_Mno_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_Mno_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_Mno_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_Mno_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sisprovisioningmodule','sis.MnoDLQ','sis.MnoDLQ','SubDeployment_Mno','null')
save()
CriarFila('UniformDistributedQueue','sisprovisioningmodule','sis.Mno','sis.Mno','SubDeployment_Mno','PriorityDestinationKey')
save()
CriarDeliveryfailure('sisprovisioningmodule','UniformDistributedQueue','sis.Mno','sis.MnoDLQ',30000,0)
CriarFileStore('Filestore_Sisgen_sisprovprd39a','./FileStore/Filestore_Sisgen_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_Sisgen_sisprovprd39a','Filestore_Sisgen_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_Sisgen_sisprovprd39b','./FileStore/Filestore_Sisgen_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_Sisgen_sisprovprd39b','Filestore_Sisgen_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_Sisgen_sisprovprd40b','./FileStore/Filestore_Sisgen_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_Sisgen_sisprovprd40b','Filestore_Sisgen_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_Sisgen_sisprovprd40c','./FileStore/Filestore_Sisgen_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_Sisgen_sisprovprd40c','Filestore_Sisgen_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_Sisgen_sisprovprd40d','./FileStore/Filestore_Sisgen_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_Sisgen_sisprovprd40d','Filestore_Sisgen_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_Sisgen_sisprovprd41a','./FileStore/Filestore_Sisgen_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_Sisgen_sisprovprd41a','Filestore_Sisgen_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_Sisgen_sisprovprd41b','./FileStore/Filestore_Sisgen_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_Sisgen_sisprovprd41b','Filestore_Sisgen_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_Sisgen_sisprovprd41c','./FileStore/Filestore_Sisgen_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_Sisgen_sisprovprd41c','Filestore_Sisgen_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sisprovisioningmodule','SubDeployment_Sisgen')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_Sisgen_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_Sisgen_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_Sisgen_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_Sisgen_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_Sisgen_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_Sisgen_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_Sisgen_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_Sisgen_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sisprovisioningmodule','sis.SisgenDLQ','sis.SisgenDLQ','SubDeployment_Sisgen','null')
save()
CriarFila('UniformDistributedQueue','sisprovisioningmodule','sis.Sisgen','sis.Sisgen','SubDeployment_Sisgen','PriorityDestinationKey')
save()
CriarDeliveryfailure('sisprovisioningmodule','UniformDistributedQueue','sis.Sisgen','sis.SisgenDLQ',30000,0)
CriarJmsModule('sismodule')
cd('/')
cd('JMSSystemResources/sismodule')
set('Targets',jarray.array([ObjectName('com.bea:Name=sisprovprd40a_sup,Type=Server'),ObjectName('com.bea:Name=sisprovisioningprd,Type=Cluster')], ObjectName))
CriarConnectionfactory('sismodule','sis.JMSConnectionFactoryNonXA','sis.JMSConnectionFactoryNonXA','all',1,'true','false',10000)
CriarConnectionfactory('sismodule','sis.JMSConnectionFactory','sis.JMSConnectionFactory','all',1,'true','true',10000)
CriarConnectionfactory('sismodule','sis.NetworkJMSConnectionFactory','sis.NetworkJMSConnectionFactory','producer',1,'true','false',10)
CriarPriorityDestinationKey('sismodule','PriorityDestinationKey','JMSPriority','Long','Descending')
CriarFileStore('Filestore_NetworkReplyAlternativeAggregation_sisprovprd39a','./FileStore/Filestore_NetworkReplyAlternativeAggregation_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternativeAggregation_sisprovprd39a','Filestore_NetworkReplyAlternativeAggregation_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_NetworkReplyAlternativeAggregation_sisprovprd39b','./FileStore/Filestore_NetworkReplyAlternativeAggregation_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternativeAggregation_sisprovprd39b','Filestore_NetworkReplyAlternativeAggregation_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_NetworkReplyAlternativeAggregation_sisprovprd40b','./FileStore/Filestore_NetworkReplyAlternativeAggregation_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternativeAggregation_sisprovprd40b','Filestore_NetworkReplyAlternativeAggregation_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_NetworkReplyAlternativeAggregation_sisprovprd40c','./FileStore/Filestore_NetworkReplyAlternativeAggregation_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternativeAggregation_sisprovprd40c','Filestore_NetworkReplyAlternativeAggregation_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_NetworkReplyAlternativeAggregation_sisprovprd40d','./FileStore/Filestore_NetworkReplyAlternativeAggregation_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternativeAggregation_sisprovprd40d','Filestore_NetworkReplyAlternativeAggregation_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_NetworkReplyAlternativeAggregation_sisprovprd41a','./FileStore/Filestore_NetworkReplyAlternativeAggregation_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternativeAggregation_sisprovprd41a','Filestore_NetworkReplyAlternativeAggregation_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_NetworkReplyAlternativeAggregation_sisprovprd41b','./FileStore/Filestore_NetworkReplyAlternativeAggregation_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternativeAggregation_sisprovprd41b','Filestore_NetworkReplyAlternativeAggregation_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_NetworkReplyAlternativeAggregation_sisprovprd41c','./FileStore/Filestore_NetworkReplyAlternativeAggregation_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternativeAggregation_sisprovprd41c','Filestore_NetworkReplyAlternativeAggregation_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sismodule','SubDeployment_NetworkReplyAlternativeAggregation')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternativeAggregation_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternativeAggregation_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternativeAggregation_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternativeAggregation_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternativeAggregation_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternativeAggregation_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternativeAggregation_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternativeAggregation_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.NetworkReplyAlternativeAggregationDLQ','sis.NetworkReplyAlternativeAggregationDLQ','SubDeployment_NetworkReplyAlternativeAggregation','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.NetworkReplyAlternativeAggregationQueue','sis.NetworkReplyAlternativeAggregationQueue','SubDeployment_NetworkReplyAlternativeAggregation','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.NetworkReplyAlternativeAggregationQueue','sis.NetworkReplyAlternativeAggregationDLQ',30000,0)
CriarFileStore('Filestore_NetworkReplyAlternative_sisprovprd39a','./FileStore/Filestore_NetworkReplyAlternative_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternative_sisprovprd39a','Filestore_NetworkReplyAlternative_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_NetworkReplyAlternative_sisprovprd39b','./FileStore/Filestore_NetworkReplyAlternative_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternative_sisprovprd39b','Filestore_NetworkReplyAlternative_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_NetworkReplyAlternative_sisprovprd40b','./FileStore/Filestore_NetworkReplyAlternative_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternative_sisprovprd40b','Filestore_NetworkReplyAlternative_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_NetworkReplyAlternative_sisprovprd40c','./FileStore/Filestore_NetworkReplyAlternative_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternative_sisprovprd40c','Filestore_NetworkReplyAlternative_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_NetworkReplyAlternative_sisprovprd40d','./FileStore/Filestore_NetworkReplyAlternative_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternative_sisprovprd40d','Filestore_NetworkReplyAlternative_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_NetworkReplyAlternative_sisprovprd41a','./FileStore/Filestore_NetworkReplyAlternative_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternative_sisprovprd41a','Filestore_NetworkReplyAlternative_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_NetworkReplyAlternative_sisprovprd41b','./FileStore/Filestore_NetworkReplyAlternative_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternative_sisprovprd41b','Filestore_NetworkReplyAlternative_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_NetworkReplyAlternative_sisprovprd41c','./FileStore/Filestore_NetworkReplyAlternative_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_NetworkReplyAlternative_sisprovprd41c','Filestore_NetworkReplyAlternative_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sismodule','SubDeployment_NetworkReplyAlternative')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternative_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternative_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternative_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternative_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternative_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternative_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternative_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyAlternative_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.NetworkReplyAlternativeDLQ','sis.NetworkReplyAlternativeDLQ','SubDeployment_NetworkReplyAlternative','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.NetworkReplyAlternativeQueue','sis.NetworkReplyAlternativeQueue','SubDeployment_NetworkReplyAlternative','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.NetworkReplyAlternativeQueue','sis.NetworkReplyAlternativeDLQ',30000,0)
CriarFileStore('Filestore_NetworkReplyDefaultAggregation_sisprovprd39a','./FileStore/Filestore_NetworkReplyDefaultAggregation_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_NetworkReplyDefaultAggregation_sisprovprd39a','Filestore_NetworkReplyDefaultAggregation_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_NetworkReplyDefaultAggregation_sisprovprd39b','./FileStore/Filestore_NetworkReplyDefaultAggregation_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_NetworkReplyDefaultAggregation_sisprovprd39b','Filestore_NetworkReplyDefaultAggregation_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_NetworkReplyDefaultAggregation_sisprovprd40b','./FileStore/Filestore_NetworkReplyDefaultAggregation_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_NetworkReplyDefaultAggregation_sisprovprd40b','Filestore_NetworkReplyDefaultAggregation_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_NetworkReplyDefaultAggregation_sisprovprd40c','./FileStore/Filestore_NetworkReplyDefaultAggregation_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_NetworkReplyDefaultAggregation_sisprovprd40c','Filestore_NetworkReplyDefaultAggregation_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_NetworkReplyDefaultAggregation_sisprovprd40d','./FileStore/Filestore_NetworkReplyDefaultAggregation_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_NetworkReplyDefaultAggregation_sisprovprd40d','Filestore_NetworkReplyDefaultAggregation_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_NetworkReplyDefaultAggregation_sisprovprd41a','./FileStore/Filestore_NetworkReplyDefaultAggregation_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_NetworkReplyDefaultAggregation_sisprovprd41a','Filestore_NetworkReplyDefaultAggregation_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_NetworkReplyDefaultAggregation_sisprovprd41b','./FileStore/Filestore_NetworkReplyDefaultAggregation_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_NetworkReplyDefaultAggregation_sisprovprd41b','Filestore_NetworkReplyDefaultAggregation_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_NetworkReplyDefaultAggregation_sisprovprd41c','./FileStore/Filestore_NetworkReplyDefaultAggregation_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_NetworkReplyDefaultAggregation_sisprovprd41c','Filestore_NetworkReplyDefaultAggregation_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sismodule','SubDeployment_NetworkReplyDefaultAggregation')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_NetworkReplyDefaultAggregation_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyDefaultAggregation_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyDefaultAggregation_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyDefaultAggregation_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyDefaultAggregation_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyDefaultAggregation_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyDefaultAggregation_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyDefaultAggregation_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.NetworkReplyDefaultAggregationDLQ','sis.NetworkReplyDefaultAggregationDLQ','SubDeployment_NetworkReplyDefaultAggregation','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.NetworkReplyDefaultAggregationQueue','sis.NetworkReplyDefaultAggregationQueue','SubDeployment_NetworkReplyDefaultAggregation','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.NetworkReplyDefaultAggregationQueue','sis.NetworkReplyDefaultAggregationDLQ',30000,0)
CriarFileStore('Filestore_NetworkReplyDefault_sisprovprd39a','./FileStore/Filestore_NetworkReplyDefault_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_NetworkReplyDefault_sisprovprd39a','Filestore_NetworkReplyDefault_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_NetworkReplyDefault_sisprovprd39b','./FileStore/Filestore_NetworkReplyDefault_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_NetworkReplyDefault_sisprovprd39b','Filestore_NetworkReplyDefault_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_NetworkReplyDefault_sisprovprd40b','./FileStore/Filestore_NetworkReplyDefault_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_NetworkReplyDefault_sisprovprd40b','Filestore_NetworkReplyDefault_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_NetworkReplyDefault_sisprovprd40c','./FileStore/Filestore_NetworkReplyDefault_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_NetworkReplyDefault_sisprovprd40c','Filestore_NetworkReplyDefault_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_NetworkReplyDefault_sisprovprd40d','./FileStore/Filestore_NetworkReplyDefault_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_NetworkReplyDefault_sisprovprd40d','Filestore_NetworkReplyDefault_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_NetworkReplyDefault_sisprovprd41a','./FileStore/Filestore_NetworkReplyDefault_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_NetworkReplyDefault_sisprovprd41a','Filestore_NetworkReplyDefault_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_NetworkReplyDefault_sisprovprd41b','./FileStore/Filestore_NetworkReplyDefault_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_NetworkReplyDefault_sisprovprd41b','Filestore_NetworkReplyDefault_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_NetworkReplyDefault_sisprovprd41c','./FileStore/Filestore_NetworkReplyDefault_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_NetworkReplyDefault_sisprovprd41c','Filestore_NetworkReplyDefault_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sismodule','SubDeployment_NetworkReplyDefault')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_NetworkReplyDefault_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyDefault_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyDefault_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyDefault_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyDefault_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyDefault_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyDefault_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkReplyDefault_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.NetworkReplyDefaultDLQ','sis.NetworkReplyDefaultDLQ','SubDeployment_NetworkReplyDefault','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.NetworkReplyDefaultQueue','sis.NetworkReplyDefaultQueue','SubDeployment_NetworkReplyDefault','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.NetworkReplyDefaultQueue','sis.NetworkReplyDefaultDLQ',30000,0)
CriarFileStore('Filestore_ProvisionerAggregation_sisprovprd39a','./FileStore/Filestore_ProvisionerAggregation_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_ProvisionerAggregation_sisprovprd39a','Filestore_ProvisionerAggregation_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_ProvisionerAggregation_sisprovprd39b','./FileStore/Filestore_ProvisionerAggregation_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_ProvisionerAggregation_sisprovprd39b','Filestore_ProvisionerAggregation_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_ProvisionerAggregation_sisprovprd40b','./FileStore/Filestore_ProvisionerAggregation_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_ProvisionerAggregation_sisprovprd40b','Filestore_ProvisionerAggregation_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_ProvisionerAggregation_sisprovprd40c','./FileStore/Filestore_ProvisionerAggregation_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_ProvisionerAggregation_sisprovprd40c','Filestore_ProvisionerAggregation_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_ProvisionerAggregation_sisprovprd40d','./FileStore/Filestore_ProvisionerAggregation_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_ProvisionerAggregation_sisprovprd40d','Filestore_ProvisionerAggregation_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_ProvisionerAggregation_sisprovprd41a','./FileStore/Filestore_ProvisionerAggregation_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_ProvisionerAggregation_sisprovprd41a','Filestore_ProvisionerAggregation_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_ProvisionerAggregation_sisprovprd41b','./FileStore/Filestore_ProvisionerAggregation_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_ProvisionerAggregation_sisprovprd41b','Filestore_ProvisionerAggregation_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_ProvisionerAggregation_sisprovprd41c','./FileStore/Filestore_ProvisionerAggregation_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_ProvisionerAggregation_sisprovprd41c','Filestore_ProvisionerAggregation_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sismodule','SubDeployment_ProvisionerAggregation')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_ProvisionerAggregation_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerAggregation_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerAggregation_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerAggregation_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerAggregation_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerAggregation_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerAggregation_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerAggregation_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerAggregationDLQ','sis.ProvisionerAggregationDLQ','SubDeployment_ProvisionerAggregation','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerAggregationQueue','sis.ProvisionerAggregationQueue','SubDeployment_ProvisionerAggregation','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.ProvisionerAggregationQueue','sis.ProvisionerAggregationDLQ',30000,0)
CriarFileStore('Filestore_ProvisionerAssyncTask_sisprovprd39a','./FileStore/Filestore_ProvisionerAssyncTask_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_ProvisionerAssyncTask_sisprovprd39a','Filestore_ProvisionerAssyncTask_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_ProvisionerAssyncTask_sisprovprd39b','./FileStore/Filestore_ProvisionerAssyncTask_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_ProvisionerAssyncTask_sisprovprd39b','Filestore_ProvisionerAssyncTask_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_ProvisionerAssyncTask_sisprovprd40b','./FileStore/Filestore_ProvisionerAssyncTask_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_ProvisionerAssyncTask_sisprovprd40b','Filestore_ProvisionerAssyncTask_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_ProvisionerAssyncTask_sisprovprd40c','./FileStore/Filestore_ProvisionerAssyncTask_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_ProvisionerAssyncTask_sisprovprd40c','Filestore_ProvisionerAssyncTask_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_ProvisionerAssyncTask_sisprovprd40d','./FileStore/Filestore_ProvisionerAssyncTask_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_ProvisionerAssyncTask_sisprovprd40d','Filestore_ProvisionerAssyncTask_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_ProvisionerAssyncTask_sisprovprd41a','./FileStore/Filestore_ProvisionerAssyncTask_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_ProvisionerAssyncTask_sisprovprd41a','Filestore_ProvisionerAssyncTask_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_ProvisionerAssyncTask_sisprovprd41b','./FileStore/Filestore_ProvisionerAssyncTask_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_ProvisionerAssyncTask_sisprovprd41b','Filestore_ProvisionerAssyncTask_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_ProvisionerAssyncTask_sisprovprd41c','./FileStore/Filestore_ProvisionerAssyncTask_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_ProvisionerAssyncTask_sisprovprd41c','Filestore_ProvisionerAssyncTask_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sismodule','SubDeployment_ProvisionerAssyncTask')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_ProvisionerAssyncTask_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerAssyncTask_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerAssyncTask_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerAssyncTask_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerAssyncTask_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerAssyncTask_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerAssyncTask_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerAssyncTask_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerAssyncTaskDLQ','sis.ProvisionerAssyncTaskDLQ','SubDeployment_ProvisionerAssyncTask','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerAssyncTaskQueue','sis.ProvisionerAssyncTaskQueue','SubDeployment_ProvisionerAssyncTask','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.ProvisionerAssyncTaskQueue','sis.ProvisionerAssyncTaskDLQ',30000,0)
CriarFileStore('Filestore_ProvisionerInAlternative_sisprovprd39a','./FileStore/Filestore_ProvisionerInAlternative_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_ProvisionerInAlternative_sisprovprd39a','Filestore_ProvisionerInAlternative_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_ProvisionerInAlternative_sisprovprd39b','./FileStore/Filestore_ProvisionerInAlternative_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_ProvisionerInAlternative_sisprovprd39b','Filestore_ProvisionerInAlternative_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_ProvisionerInAlternative_sisprovprd40b','./FileStore/Filestore_ProvisionerInAlternative_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_ProvisionerInAlternative_sisprovprd40b','Filestore_ProvisionerInAlternative_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_ProvisionerInAlternative_sisprovprd40c','./FileStore/Filestore_ProvisionerInAlternative_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_ProvisionerInAlternative_sisprovprd40c','Filestore_ProvisionerInAlternative_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_ProvisionerInAlternative_sisprovprd40d','./FileStore/Filestore_ProvisionerInAlternative_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_ProvisionerInAlternative_sisprovprd40d','Filestore_ProvisionerInAlternative_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_ProvisionerInAlternative_sisprovprd41a','./FileStore/Filestore_ProvisionerInAlternative_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_ProvisionerInAlternative_sisprovprd41a','Filestore_ProvisionerInAlternative_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_ProvisionerInAlternative_sisprovprd41b','./FileStore/Filestore_ProvisionerInAlternative_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_ProvisionerInAlternative_sisprovprd41b','Filestore_ProvisionerInAlternative_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_ProvisionerInAlternative_sisprovprd41c','./FileStore/Filestore_ProvisionerInAlternative_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_ProvisionerInAlternative_sisprovprd41c','Filestore_ProvisionerInAlternative_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sismodule','SubDeployment_ProvisionerInAlternative')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_ProvisionerInAlternative_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerInAlternative_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerInAlternative_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerInAlternative_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerInAlternative_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerInAlternative_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerInAlternative_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerInAlternative_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerInAlternativeDLQ','sis.ProvisionerInAlternativeDLQ','SubDeployment_ProvisionerInAlternative','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerInAlternativeQueue','sis.ProvisionerInAlternativeQueue','SubDeployment_ProvisionerInAlternative','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.ProvisionerInAlternativeQueue','sis.ProvisionerInAlternativeDLQ',30000,0)
CriarFileStore('Filestore_ProvisionerInDefault_sisprovprd39a','./FileStore/Filestore_ProvisionerInDefault_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_ProvisionerInDefault_sisprovprd39a','Filestore_ProvisionerInDefault_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_ProvisionerInDefault_sisprovprd39b','./FileStore/Filestore_ProvisionerInDefault_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_ProvisionerInDefault_sisprovprd39b','Filestore_ProvisionerInDefault_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_ProvisionerInDefault_sisprovprd40b','./FileStore/Filestore_ProvisionerInDefault_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_ProvisionerInDefault_sisprovprd40b','Filestore_ProvisionerInDefault_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_ProvisionerInDefault_sisprovprd40c','./FileStore/Filestore_ProvisionerInDefault_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_ProvisionerInDefault_sisprovprd40c','Filestore_ProvisionerInDefault_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_ProvisionerInDefault_sisprovprd40d','./FileStore/Filestore_ProvisionerInDefault_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_ProvisionerInDefault_sisprovprd40d','Filestore_ProvisionerInDefault_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_ProvisionerInDefault_sisprovprd41a','./FileStore/Filestore_ProvisionerInDefault_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_ProvisionerInDefault_sisprovprd41a','Filestore_ProvisionerInDefault_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_ProvisionerInDefault_sisprovprd41b','./FileStore/Filestore_ProvisionerInDefault_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_ProvisionerInDefault_sisprovprd41b','Filestore_ProvisionerInDefault_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_ProvisionerInDefault_sisprovprd41c','./FileStore/Filestore_ProvisionerInDefault_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_ProvisionerInDefault_sisprovprd41c','Filestore_ProvisionerInDefault_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sismodule','SubDeployment_ProvisionerInDefault')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_ProvisionerInDefault_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerInDefault_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerInDefault_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerInDefault_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerInDefault_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerInDefault_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerInDefault_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerInDefault_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerInDefaultDLQ','sis.ProvisionerInDefaultDLQ','SubDeployment_ProvisionerInDefault','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerInDefaultQueue','sis.ProvisionerInDefaultQueue','SubDeployment_ProvisionerInDefault','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.ProvisionerInDefaultQueue','sis.ProvisionerInDefaultDLQ',30000,0)
CriarFileStore('Filestore_ProvisionerIn_sisprovprd39a','./FileStore/Filestore_ProvisionerIn_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_ProvisionerIn_sisprovprd39a','Filestore_ProvisionerIn_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_ProvisionerIn_sisprovprd39b','./FileStore/Filestore_ProvisionerIn_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_ProvisionerIn_sisprovprd39b','Filestore_ProvisionerIn_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_ProvisionerIn_sisprovprd40b','./FileStore/Filestore_ProvisionerIn_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_ProvisionerIn_sisprovprd40b','Filestore_ProvisionerIn_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_ProvisionerIn_sisprovprd40c','./FileStore/Filestore_ProvisionerIn_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_ProvisionerIn_sisprovprd40c','Filestore_ProvisionerIn_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_ProvisionerIn_sisprovprd40d','./FileStore/Filestore_ProvisionerIn_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_ProvisionerIn_sisprovprd40d','Filestore_ProvisionerIn_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_ProvisionerIn_sisprovprd41a','./FileStore/Filestore_ProvisionerIn_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_ProvisionerIn_sisprovprd41a','Filestore_ProvisionerIn_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_ProvisionerIn_sisprovprd41b','./FileStore/Filestore_ProvisionerIn_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_ProvisionerIn_sisprovprd41b','Filestore_ProvisionerIn_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_ProvisionerIn_sisprovprd41c','./FileStore/Filestore_ProvisionerIn_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_ProvisionerIn_sisprovprd41c','Filestore_ProvisionerIn_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sismodule','SubDeployment_ProvisionerIn')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_ProvisionerIn_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerIn_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerIn_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerIn_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerIn_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerIn_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerIn_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerIn_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerInDLQ','sis.ProvisionerInDLQ','SubDeployment_ProvisionerIn','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerInQueue','sis.ProvisionerInQueue','SubDeployment_ProvisionerIn','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.ProvisionerInQueue','sis.ProvisionerInDLQ',30000,0)
CriarFileStore('Filestore_ProvisionerOut_sisprovprd39a','./FileStore/Filestore_ProvisionerOut_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_ProvisionerOut_sisprovprd39a','Filestore_ProvisionerOut_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_ProvisionerOut_sisprovprd39b','./FileStore/Filestore_ProvisionerOut_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_ProvisionerOut_sisprovprd39b','Filestore_ProvisionerOut_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_ProvisionerOut_sisprovprd40b','./FileStore/Filestore_ProvisionerOut_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_ProvisionerOut_sisprovprd40b','Filestore_ProvisionerOut_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_ProvisionerOut_sisprovprd40c','./FileStore/Filestore_ProvisionerOut_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_ProvisionerOut_sisprovprd40c','Filestore_ProvisionerOut_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_ProvisionerOut_sisprovprd40d','./FileStore/Filestore_ProvisionerOut_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_ProvisionerOut_sisprovprd40d','Filestore_ProvisionerOut_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_ProvisionerOut_sisprovprd41a','./FileStore/Filestore_ProvisionerOut_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_ProvisionerOut_sisprovprd41a','Filestore_ProvisionerOut_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_ProvisionerOut_sisprovprd41b','./FileStore/Filestore_ProvisionerOut_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_ProvisionerOut_sisprovprd41b','Filestore_ProvisionerOut_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_ProvisionerOut_sisprovprd41c','./FileStore/Filestore_ProvisionerOut_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_ProvisionerOut_sisprovprd41c','Filestore_ProvisionerOut_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sismodule','SubDeployment_ProvisionerOut')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_ProvisionerOut_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerOut_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerOut_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerOut_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerOut_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerOut_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerOut_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_ProvisionerOut_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerOutDLQ','sis.ProvisionerOutDLQ','SubDeployment_ProvisionerOut','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.ProvisionerOutQueue','sis.ProvisionerOutQueue','SubDeployment_ProvisionerOut','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.ProvisionerOutQueue','sis.ProvisionerOutDLQ',30000,0)
CriarFileStore('Filestore_WorkflowDefinition_sisprovprd39a','./FileStore/Filestore_WorkflowDefinition_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_WorkflowDefinition_sisprovprd39a','Filestore_WorkflowDefinition_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_WorkflowDefinition_sisprovprd39b','./FileStore/Filestore_WorkflowDefinition_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_WorkflowDefinition_sisprovprd39b','Filestore_WorkflowDefinition_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_WorkflowDefinition_sisprovprd40b','./FileStore/Filestore_WorkflowDefinition_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_WorkflowDefinition_sisprovprd40b','Filestore_WorkflowDefinition_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_WorkflowDefinition_sisprovprd40c','./FileStore/Filestore_WorkflowDefinition_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_WorkflowDefinition_sisprovprd40c','Filestore_WorkflowDefinition_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_WorkflowDefinition_sisprovprd40d','./FileStore/Filestore_WorkflowDefinition_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_WorkflowDefinition_sisprovprd40d','Filestore_WorkflowDefinition_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_WorkflowDefinition_sisprovprd41a','./FileStore/Filestore_WorkflowDefinition_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_WorkflowDefinition_sisprovprd41a','Filestore_WorkflowDefinition_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_WorkflowDefinition_sisprovprd41b','./FileStore/Filestore_WorkflowDefinition_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_WorkflowDefinition_sisprovprd41b','Filestore_WorkflowDefinition_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_WorkflowDefinition_sisprovprd41c','./FileStore/Filestore_WorkflowDefinition_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_WorkflowDefinition_sisprovprd41c','Filestore_WorkflowDefinition_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sismodule','SubDeployment_WorkflowDefinition')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_WorkflowDefinition_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_WorkflowDefinition_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_WorkflowDefinition_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_WorkflowDefinition_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_WorkflowDefinition_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_WorkflowDefinition_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_WorkflowDefinition_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_WorkflowDefinition_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.WorkflowDefinitionDLQ','sis.WorkflowDefinitionDLQ','SubDeployment_WorkflowDefinition','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.WorkflowDefinitionQueue','sis.WorkflowDefinitionQueue','SubDeployment_WorkflowDefinition','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.WorkflowDefinitionQueue','sis.WorkflowDefinitionDLQ',30000,0)
CriarFileStore('Filestore_EventHistory_sisprovprd39a','./FileStore/Filestore_EventHistory_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_EventHistory_sisprovprd39a','Filestore_EventHistory_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_EventHistory_sisprovprd39b','./FileStore/Filestore_EventHistory_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_EventHistory_sisprovprd39b','Filestore_EventHistory_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_EventHistory_sisprovprd40b','./FileStore/Filestore_EventHistory_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_EventHistory_sisprovprd40b','Filestore_EventHistory_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_EventHistory_sisprovprd40c','./FileStore/Filestore_EventHistory_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_EventHistory_sisprovprd40c','Filestore_EventHistory_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_EventHistory_sisprovprd40d','./FileStore/Filestore_EventHistory_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_EventHistory_sisprovprd40d','Filestore_EventHistory_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_EventHistory_sisprovprd41a','./FileStore/Filestore_EventHistory_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_EventHistory_sisprovprd41a','Filestore_EventHistory_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_EventHistory_sisprovprd41b','./FileStore/Filestore_EventHistory_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_EventHistory_sisprovprd41b','Filestore_EventHistory_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_EventHistory_sisprovprd41c','./FileStore/Filestore_EventHistory_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_EventHistory_sisprovprd41c','Filestore_EventHistory_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sismodule','SubDeployment_EventHistory')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_EventHistory_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_EventHistory_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_EventHistory_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_EventHistory_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_EventHistory_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_EventHistory_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_EventHistory_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_EventHistory_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.EventHistoryDLQ','sis.EventHistoryDLQ','SubDeployment_EventHistory','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.EventHistoryQueue','sis.EventHistoryQueue','SubDeployment_EventHistory','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.EventHistoryQueue','sis.EventHistoryDLQ',30000,0)
CriarFileStore('Filestore_NetworkOut_sisprovprd39a','./FileStore/Filestore_NetworkOut_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_NetworkOut_sisprovprd39a','Filestore_NetworkOut_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_NetworkOut_sisprovprd39b','./FileStore/Filestore_NetworkOut_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_NetworkOut_sisprovprd39b','Filestore_NetworkOut_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_NetworkOut_sisprovprd40b','./FileStore/Filestore_NetworkOut_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_NetworkOut_sisprovprd40b','Filestore_NetworkOut_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_NetworkOut_sisprovprd40c','./FileStore/Filestore_NetworkOut_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_NetworkOut_sisprovprd40c','Filestore_NetworkOut_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_NetworkOut_sisprovprd40d','./FileStore/Filestore_NetworkOut_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_NetworkOut_sisprovprd40d','Filestore_NetworkOut_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_NetworkOut_sisprovprd41a','./FileStore/Filestore_NetworkOut_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_NetworkOut_sisprovprd41a','Filestore_NetworkOut_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_NetworkOut_sisprovprd41b','./FileStore/Filestore_NetworkOut_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_NetworkOut_sisprovprd41b','Filestore_NetworkOut_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_NetworkOut_sisprovprd41c','./FileStore/Filestore_NetworkOut_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_NetworkOut_sisprovprd41c','Filestore_NetworkOut_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sismodule','SubDeployment_NetworkOut')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_NetworkOut_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkOut_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkOut_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkOut_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkOut_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkOut_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkOut_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkOut_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.NetworkOutDLQ','sis.NetworkOutDLQ','SubDeployment_NetworkOut','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.NetworkOutQueue','sis.NetworkOutQueue','SubDeployment_NetworkOut','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.NetworkOutQueue','sis.NetworkOutDLQ',30000,0)
CriarFileStore('Filestore_NetworkIn_sisprovprd39a','./FileStore/Filestore_NetworkIn_sisprovprd39a','sisprovprd39a','Server')
CriarJmsServer('JMSServer_NetworkIn_sisprovprd39a','Filestore_NetworkIn_sisprovprd39a','sisprovprd39a','Server')
CriarFileStore('Filestore_NetworkIn_sisprovprd39b','./FileStore/Filestore_NetworkIn_sisprovprd39b','sisprovprd39b','Server')
CriarJmsServer('JMSServer_NetworkIn_sisprovprd39b','Filestore_NetworkIn_sisprovprd39b','sisprovprd39b','Server')
CriarFileStore('Filestore_NetworkIn_sisprovprd40b','./FileStore/Filestore_NetworkIn_sisprovprd40b','sisprovprd40b','Server')
CriarJmsServer('JMSServer_NetworkIn_sisprovprd40b','Filestore_NetworkIn_sisprovprd40b','sisprovprd40b','Server')
CriarFileStore('Filestore_NetworkIn_sisprovprd40c','./FileStore/Filestore_NetworkIn_sisprovprd40c','sisprovprd40c','Server')
CriarJmsServer('JMSServer_NetworkIn_sisprovprd40c','Filestore_NetworkIn_sisprovprd40c','sisprovprd40c','Server')
CriarFileStore('Filestore_NetworkIn_sisprovprd40d','./FileStore/Filestore_NetworkIn_sisprovprd40d','sisprovprd40d','Server')
CriarJmsServer('JMSServer_NetworkIn_sisprovprd40d','Filestore_NetworkIn_sisprovprd40d','sisprovprd40d','Server')
CriarFileStore('Filestore_NetworkIn_sisprovprd41a','./FileStore/Filestore_NetworkIn_sisprovprd41a','sisprovprd41a','Server')
CriarJmsServer('JMSServer_NetworkIn_sisprovprd41a','Filestore_NetworkIn_sisprovprd41a','sisprovprd41a','Server')
CriarFileStore('Filestore_NetworkIn_sisprovprd41b','./FileStore/Filestore_NetworkIn_sisprovprd41b','sisprovprd41b','Server')
CriarJmsServer('JMSServer_NetworkIn_sisprovprd41b','Filestore_NetworkIn_sisprovprd41b','sisprovprd41b','Server')
CriarFileStore('Filestore_NetworkIn_sisprovprd41c','./FileStore/Filestore_NetworkIn_sisprovprd41c','sisprovprd41c','Server')
CriarJmsServer('JMSServer_NetworkIn_sisprovprd41c','Filestore_NetworkIn_sisprovprd41c','sisprovprd41c','Server')
CriarSubDeployment('sismodule','SubDeployment_NetworkIn')
set('Targets',jarray.array([ObjectName('com.bea:Name=JMSServer_NetworkIn_sisprovprd39a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkIn_sisprovprd39b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkIn_sisprovprd40b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkIn_sisprovprd40c,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkIn_sisprovprd40d,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkIn_sisprovprd41a,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkIn_sisprovprd41b,Type=JMSServer'),ObjectName('com.bea:Name=JMSServer_NetworkIn_sisprovprd41c,Type=JMSServer')], ObjectName))
activate()
edit()
startEdit()
CriarFila('UniformDistributedQueue','sismodule','sis.NetworkInDLQ','sis.NetworkInDLQ','SubDeployment_NetworkIn','null')
save()
CriarFila('UniformDistributedQueue','sismodule','sis.NetworkInQueue','sis.NetworkInQueue','SubDeployment_NetworkIn','PriorityDestinationKey')
save()
CriarDeliveryfailure('sismodule','UniformDistributedQueue','sis.NetworkInQueue','sis.NetworkInDLQ',30000,0)
CriarBridgeTarget('EventHistoryOri','eis.jms.WLSConnectionFactoryJNDIXA','sis.NetworkJMSConnectionFactory','t3://msisprd39:57003,msisprd39:57005,msisprd40:57003,msisprd40:57005,msisprd40:57009,msisprd41:57003,msisprd41:57005,msisprd41:57007','weblogic','welcome1','sis.EventHistoryQueue')
CriarBridgeTarget('EventHistoryDest','eis.jms.WLSConnectionFactoryJNDIXA','sis.JMSConnectionFactory','t3://msisprd38:37005,msisprd38:37007,msisprd38:37009,msisprd39:37003,msisprd39:37005,msisprd39:37007,msisprd40:37003,msisprd40:37003','weblogic','welcome1','sis.EventHistoryQueue')
CriarBridge('EventHistoryBridge','Exactly-once','true','null','EventHistoryOri','EventHistoryDest','true')
set('Targets',jarray.array([ObjectName('com.bea:Name=sisprovisioningprd,Type=Cluster')], ObjectName))
CriarBridgeTarget('NetworkInOri','eis.jms.WLSConnectionFactoryJNDIXA','sis.JMSConnectionFactory','t3://msisprd39:57003,msisprd39:57005,msisprd40:57003,msisprd40:57005,msisprd40:57009,msisprd41:57003,msisprd41:57005,msisprd41:57007','weblogic','welcome1','sis.NetworkInQueue')
CriarBridgeTarget('NetworkInDest','eis.jms.WLSConnectionFactoryJNDIXA','sis.JMSConnectionFactory','t3://msisprd40:47003,msisprd40:47005,msisprd40:47007,msisprd41:47003,msisprd41:47005,msisprd41:47007,msisprd42:47003,msisprd42:47005,msisprd42:47007','weblogic','welcome1','sis.NetworkInQueue')
CriarBridge('NetworkInBridge','Exactly-once','true','null','NetworkInOri','NetworkInDest','true')
set('Targets',jarray.array([ObjectName('com.bea:Name=sisprovisioningprd,Type=Cluster')], ObjectName))
CriarBridgeTarget('NetworkOutOri','eis.jms.WLSConnectionFactoryJNDIXA','sis.JMSConnectionFactory','t3://msisprd39:57003,msisprd39:57005,msisprd40:57003,msisprd40:57005,msisprd40:57009,msisprd41:57003,msisprd41:57005,msisprd41:57007','weblogic','welcome1','sis.NetworkOutQueue')
CriarBridgeTarget('NetworkOutDest','eis.jms.WLSConnectionFactoryJNDIXA','sis.JMSConnectionFactory','t3://msisprd40:47003,msisprd40:47005,msisprd40:47007,msisprd41:47003,msisprd41:47005,msisprd41:47007,msisprd42:47003,msisprd42:47005,msisprd42:47007','weblogic','welcome1','sis.NetworkOutQueue')
CriarBridge('NetworkOutBridge','Exactly-once','true','null','NetworkOutOri','NetworkOutDest','true')
set('Targets',jarray.array([ObjectName('com.bea:Name=sisprovisioningprd,Type=Cluster')], ObjectName))
save()
activate()
exit()
